packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  # all packages in subdirs of tools/
  - 'tools/**'
  # exclude packages that are inside test directories
  - '!**/test/**'
  # exclude testing
  - '!packages/testing/**'
