packages:
  - packages/*
  - tools/**
  - '!**/test/**'
  - '!packages/testing/**'

ignoredBuiltDependencies:
  - '@swc/core'
  - core-js
  - cpu-features
  - esbuild
  - fsevents
  - ssh2

minimumReleaseAge: 4320

onlyBuiltDependencies:
  - better-sqlite3
