packages:
  - packages/*
  - tools/**
  - '!**/test/**'
  - '!packages/testing/**'

minimumReleaseAge: 1440

overrides:
  '=': link:../../../.local/share/pnpm/global/5/node_modules/=
  node-forge: 1.3.2
  request>form-data: ^2.5.5
