import * as Adaptor from './Adaptor';
export default Adaptor;
export * from './Adaptor';
declare const b: {
    appointment(type: "SzAppointment", props: import("./profiles/SzAppointment").Appointment_SzAppointment_Props): any;
    condition(type: "SzCondition", props: import("./profiles/SzCondition").Condition_SzCondition_Props): any;
    encounter(type: "SzEncounter", props: import("./profiles/SzEncounter").Encounter_SzEncounter_Props): any;
    episodeOfCare(type: "SzEpisodeOfCare", props: import("./profiles/SzEpisodeOfCare").EpisodeOfCare_SzEpisodeOfCare_Props): any;
    extension(type: "SzAuthorizerExtension", props: import("./profiles/SzAuthorizerExtension").Extension_SzAuthorizerExtension_Props): any;
    extension(type: "SzChiefdomExtension", props: import("./profiles/SzChiefdomExtension").Extension_SzChiefdomExtension_Props): any;
    extension(type: "SzInkhundlaExtension", props: import("./profiles/SzInkhundlaExtension").Extension_SzInkhundlaExtension_Props): any;
    extension(type: "SzLocationCodeExtension", props: import("./profiles/SzLocationCodeExtension").Extension_SzLocationCodeExtension_Props): any;
    extension(type: "SzReferralRecipientExtension", props: import("./profiles/SzReferralRecipientExtension").Extension_SzReferralRecipientExtension_Props): any;
    extension(type: "SzRegistrationDate", props: import("./profiles/SzRegistrationDate").Extension_SzRegistrationDate_Props): any;
    extension(type: "SzTestingLabExtension", props: import("./profiles/SzTestingLabExtension").Extension_SzTestingLabExtension_Props): any;
    location(type: "SzLocation", props: import("./profiles/SzLocation").Location_SzLocation_Props): any;
    medication(type: "SzMedication", props: import("./profiles/SzMedication").Medication_SzMedication_Props): any;
    medicationDispense(type: "SzMedicationDispense", props: import("./profiles/SzMedicationDispense").MedicationDispense_SzMedicationDispense_Props): any;
    medicationRequest(type: "SzMedicationRequest", props: import("./profiles/SzMedicationRequest").MedicationRequest_SzMedicationRequest_Props): any;
    observation(type: "SzCauseOfDeath", props: import("./profiles/SzCauseOfDeath").Observation_SzCauseOfDeath_Props): any;
    observation(type: "SzClinicalObservation", props: import("./profiles/SzClinicalObservation").Observation_SzClinicalObservation_Props): any;
    observation(type: "SzLabResult", props: import("./profiles/SzLabResult").Observation_SzLabResult_Props): any;
    observation(type: "SzMannerOfDeath", props: import("./profiles/SzMannerOfDeath").Observation_SzMannerOfDeath_Props): any;
    observation(type: "SzVitalSigns", props: import("./profiles/SzVitalSigns").Observation_SzVitalSigns_Props): any;
    organization(type: "SzOrganization", props: import("./profiles/SzOrganization").Organization_SzOrganization_Props): any;
    patient(type: "SzPatient", props: import("./profiles/SzPatient").Patient_SzPatient_Props): any;
    practitioner(type: "SzPractitioner", props: import("./profiles/SzPractitioner").Practitioner_SzPractitioner_Props): any;
    procedure(type: "SzProcedure", props: import("./profiles/SzProcedure").Procedure_SzProcedure_Props): any;
    serviceRequest(type: "SzLabRequest", props: import("./profiles/SzLabRequest").ServiceRequest_SzLabRequest_Props): any;
    serviceRequest(type: "SzReferral", props: import("./profiles/SzReferral").ServiceRequest_SzReferral_Props): any;
    specimen(type: "SzLabSpecimen", props: import("./profiles/SzLabSpecimen").Specimen_SzLabSpecimen_Props): any;
    mapSystems: (obj: any) => any;
    setSystemMap: (newMappings: any) => void;
    extendSystemMap: (newMappings: any) => void;
    identifier: (id: any, ...ext: any[]) => any;
    id: (id: any, ...ext: any[]) => any;
    addExtension: (resource: any, url: any, value: any) => void;
    findExtension: (obj: any, targetUrl: any, path: any) => any;
    coding: (code: any, system: any) => {
        code: any;
        system: any;
    };
    c: (code: any, system: any) => {
        code: any;
        system: any;
    };
    value: (value: any, system: any, ...extra: any[]) => any;
    concept: (text: any, ...codings: any[]) => {};
    cc: (text: any, ...codings: any[]) => {};
    reference: (ref: any, opts: any) => any;
    ref: (ref: any, opts: any) => any;
    composite: (object: any, key: any, value: any) => void;
};
export { b, b as builders };
