import { b as dt } from "@openfn/language-fhir-4";
import type { builders as FHIR } from "@openfn/language-fhir-4";
export declare type Appointment_SzAppointment_Props = {
    appointmentType?: FHIR.CodeableConcept;
    basedOn?: FHIR.Reference[];
    cancelationReason?: FHIR.CodeableConcept;
    comment?: string;
    contained?: any[];
    created?: string;
    description?: string;
    end?: string;
    extension?: FHIR.Extension[];
    id?: string;
    identifier?: FHIR.Identifier[];
    implicitRules?: string;
    language?: string;
    meta?: FHIR.Meta;
    minutesDuration?: number;
    modifierExtension?: FHIR.Extension[];
    participant?: FHIR.BackboneElement[];
    patientInstruction?: string;
    priority?: number;
    reasonCode?: FHIR.CodeableConcept[];
    reasonReference?: FHIR.Reference[];
    requestedPeriod?: FHIR.Period[];
    serviceCategory?: FHIR.CodeableConcept[];
    serviceType?: FHIR.CodeableConcept[];
    slot?: FHIR.Reference[];
    specialty?: FHIR.CodeableConcept[];
    start?: string;
    status?: string;
    supportingInformation?: FHIR.Reference[];
    text?: FHIR.Narrative;
    [key: string]: any;
};
export default function (props: Partial<Appointment_SzAppointment_Props>): {
    appointmentType?: dt.CodeableConcept;
    basedOn?: dt.Reference[];
    cancelationReason?: dt.CodeableConcept;
    comment?: string;
    contained?: any[];
    created?: string;
    description?: string;
    end?: string;
    extension?: dt.Extension[];
    id?: string;
    identifier?: dt.Identifier[];
    implicitRules?: string;
    language?: string;
    meta?: dt.Meta;
    minutesDuration?: number;
    modifierExtension?: dt.Extension[];
    participant?: dt.BackboneElement[];
    patientInstruction?: string;
    priority?: number;
    reasonCode?: dt.CodeableConcept[];
    reasonReference?: dt.Reference[];
    requestedPeriod?: dt.Period[];
    serviceCategory?: dt.CodeableConcept[];
    serviceType?: dt.CodeableConcept[];
    slot?: dt.Reference[];
    specialty?: dt.CodeableConcept[];
    start?: string;
    status?: string;
    supportingInformation?: dt.Reference[];
    text?: dt.Narrative;
    resourceType: string;
};
