import { b as dt } from "@openfn/language-fhir-4";
import type { builders as FHIR } from "@openfn/language-fhir-4";
export declare type Condition_SzCondition_Props = {
    abatement?: string | FHIR.Age | FHIR.Period | FHIR.Range;
    asserter?: FHIR.Reference;
    bodySite?: FHIR.CodeableConcept[];
    category?: FHIR.CodeableConcept[];
    clinicalStatus?: FHIR.CodeableConcept;
    code?: FHIR.CodeableConcept;
    contained?: any[];
    encounter?: FHIR.Reference;
    evidence?: FHIR.BackboneElement[];
    extension?: FHIR.Extension[];
    id?: string;
    identifier?: FHIR.Identifier[];
    implicitRules?: string;
    language?: string;
    meta?: FHIR.Meta;
    modifierExtension?: FHIR.Extension[];
    note?: FHIR.Annotation[];
    onset?: string;
    recordedDate?: string;
    recorder?: FHIR.Reference;
    severity?: FHIR.CodeableConcept;
    stage?: FHIR.BackboneElement[];
    subject?: FHIR.Reference;
    text?: FHIR.Narrative;
    verificationStatus?: FHIR.CodeableConcept;
    [key: string]: any;
};
export default function (props: Partial<Condition_SzCondition_Props>): {
    abatement?: string | dt.Period | dt.Age | dt.Range;
    asserter?: dt.Reference;
    bodySite?: dt.CodeableConcept[];
    category?: dt.CodeableConcept[];
    clinicalStatus?: dt.CodeableConcept;
    code?: dt.CodeableConcept;
    contained?: any[];
    encounter?: dt.Reference;
    evidence?: dt.BackboneElement[];
    extension?: dt.Extension[];
    id?: string;
    identifier?: dt.Identifier[];
    implicitRules?: string;
    language?: string;
    meta?: dt.Meta;
    modifierExtension?: dt.Extension[];
    note?: dt.Annotation[];
    onset?: string;
    recordedDate?: string;
    recorder?: dt.Reference;
    severity?: dt.CodeableConcept;
    stage?: dt.BackboneElement[];
    subject?: dt.Reference;
    text?: dt.Narrative;
    verificationStatus?: dt.CodeableConcept;
    resourceType: string;
};
