import { b as dt } from "@openfn/language-fhir-4";
import type { builders as FHIR } from "@openfn/language-fhir-4";
export declare type Encounter_SzEncounter_Props = {
    account?: FHIR.Reference[];
    appointment?: FHIR.Reference[];
    basedOn?: FHIR.Reference[];
    class?: FHIR.Coding;
    classHistory?: FHIR.BackboneElement[];
    contained?: any[];
    diagnosis?: FHIR.BackboneElement[];
    episodeOfCare?: FHIR.Reference[];
    extension?: FHIR.Extension[];
    hospitalization?: FHIR.BackboneElement;
    id?: string;
    identifier?: FHIR.Identifier[];
    implicitRules?: string;
    language?: string;
    length?: FHIR.Duration;
    location?: FHIR.BackboneElement[];
    meta?: FHIR.Meta;
    modifierExtension?: FHIR.Extension[];
    partOf?: FHIR.Reference;
    participant?: FHIR.BackboneElement[];
    period?: FHIR.Period;
    priority?: FHIR.CodeableConcept;
    reasonCode?: FHIR.CodeableConcept[];
    reasonReference?: FHIR.Reference[];
    serviceProvider?: FHIR.Reference;
    serviceType?: FHIR.CodeableConcept;
    status?: string;
    statusHistory?: FHIR.BackboneElement[];
    subject?: FHIR.Reference;
    text?: FHIR.Narrative;
    type?: FHIR.CodeableConcept[];
    [key: string]: any;
};
export default function (props: Partial<Encounter_SzEncounter_Props>): {
    account?: dt.Reference[];
    appointment?: dt.Reference[];
    basedOn?: dt.Reference[];
    class?: dt.Coding;
    classHistory?: dt.BackboneElement[];
    contained?: any[];
    diagnosis?: dt.BackboneElement[];
    episodeOfCare?: dt.Reference[];
    extension?: dt.Extension[];
    hospitalization?: dt.BackboneElement;
    id?: string;
    identifier?: dt.Identifier[];
    implicitRules?: string;
    language?: string;
    length?: dt.Duration;
    location?: dt.BackboneElement[];
    meta?: dt.Meta;
    modifierExtension?: dt.Extension[];
    partOf?: dt.Reference;
    participant?: dt.BackboneElement[];
    period?: dt.Period;
    priority?: dt.CodeableConcept;
    reasonCode?: dt.CodeableConcept[];
    reasonReference?: dt.Reference[];
    serviceProvider?: dt.Reference;
    serviceType?: dt.CodeableConcept;
    status?: string;
    statusHistory?: dt.BackboneElement[];
    subject?: dt.Reference;
    text?: dt.Narrative;
    type?: dt.CodeableConcept[];
    resourceType: string;
};
