import { b as dt } from "@openfn/language-fhir-4";
import type { builders as FHIR } from "@openfn/language-fhir-4";
export declare type EpisodeOfCare_SzEpisodeOfCare_Props = {
    account?: FHIR.Reference[];
    careManager?: FHIR.Reference;
    contained?: any[];
    diagnosis?: FHIR.BackboneElement[];
    extension?: FHIR.Extension[];
    id?: string;
    identifier?: FHIR.Identifier[];
    implicitRules?: string;
    language?: string;
    managingOrganization?: FHIR.Reference;
    meta?: FHIR.Meta;
    modifierExtension?: FHIR.Extension[];
    patient?: FHIR.Reference;
    period?: FHIR.Period;
    referralRequest?: FHIR.Reference[];
    status?: string;
    statusHistory?: FHIR.BackboneElement[];
    team?: FHIR.Reference[];
    text?: FHIR.Narrative;
    type?: FHIR.CodeableConcept[];
    [key: string]: any;
};
export default function (props: Partial<EpisodeOfCare_SzEpisodeOfCare_Props>): {
    account?: dt.Reference[];
    careManager?: dt.Reference;
    contained?: any[];
    diagnosis?: dt.BackboneElement[];
    extension?: dt.Extension[];
    id?: string;
    identifier?: dt.Identifier[];
    implicitRules?: string;
    language?: string;
    managingOrganization?: dt.Reference;
    meta?: dt.Meta;
    modifierExtension?: dt.Extension[];
    patient?: dt.Reference;
    period?: dt.Period;
    referralRequest?: dt.Reference[];
    status?: string;
    statusHistory?: dt.BackboneElement[];
    team?: dt.Reference[];
    text?: dt.Narrative;
    type?: dt.CodeableConcept[];
    resourceType: string;
};
