import { b as dt } from "@openfn/language-fhir-4";
import type { builders as FHIR } from "@openfn/language-fhir-4";
export declare type ServiceRequest_SzLabRequest_Props = {
    asNeeded?: boolean | FHIR.CodeableConcept;
    authoredOn?: string;
    basedOn?: FHIR.Reference[];
    bodySite?: FHIR.CodeableConcept[];
    category?: FHIR.CodeableConcept[];
    code?: FHIR.CodeableConcept;
    contained?: any[];
    doNotPerform?: boolean;
    encounter?: FHIR.Reference;
    extension?: FHIR.Extension[];
    id?: string;
    identifier?: FHIR.Identifier[];
    implicitRules?: string;
    instantiatesCanonical?: any[];
    instantiatesUri?: string[];
    insurance?: FHIR.Reference[];
    intent?: string;
    language?: string;
    locationCode?: FHIR.CodeableConcept[];
    locationReference?: FHIR.Reference[];
    meta?: FHIR.Meta;
    modifierExtension?: FHIR.Extension[];
    note?: FHIR.Annotation[];
    occurrence?: string | FHIR.Period | FHIR.Timing;
    orderDetail?: FHIR.CodeableConcept[];
    patientInstruction?: string;
    performer?: FHIR.Reference[];
    performerType?: FHIR.CodeableConcept;
    priority?: string;
    quantity?: FHIR.Quantity | FHIR.Ratio | FHIR.Range;
    reasonCode?: FHIR.CodeableConcept[];
    reasonReference?: FHIR.Reference[];
    relevantHistory?: FHIR.Reference[];
    replaces?: FHIR.Reference[];
    requester?: FHIR.Reference;
    requisition?: FHIR.Identifier;
    specimen?: FHIR.Reference[];
    status?: string;
    subject?: FHIR.Reference;
    supportingInfo?: FHIR.Reference[];
    text?: FHIR.Narrative;
    [key: string]: any;
};
export default function (props: Partial<ServiceRequest_SzLabRequest_Props>): {
    asNeeded?: boolean | dt.CodeableConcept;
    authoredOn?: string;
    basedOn?: dt.Reference[];
    bodySite?: dt.CodeableConcept[];
    category?: dt.CodeableConcept[];
    code?: dt.CodeableConcept;
    contained?: any[];
    doNotPerform?: boolean;
    encounter?: dt.Reference;
    extension?: dt.Extension[];
    id?: string;
    identifier?: dt.Identifier[];
    implicitRules?: string;
    instantiatesCanonical?: any[];
    instantiatesUri?: string[];
    insurance?: dt.Reference[];
    intent?: string;
    language?: string;
    locationCode?: dt.CodeableConcept[];
    locationReference?: dt.Reference[];
    meta?: dt.Meta;
    modifierExtension?: dt.Extension[];
    note?: dt.Annotation[];
    occurrence?: string | dt.Period | dt.Timing;
    orderDetail?: dt.CodeableConcept[];
    patientInstruction?: string;
    performer?: dt.Reference[];
    performerType?: dt.CodeableConcept;
    priority?: string;
    quantity?: dt.Range | dt.Ratio | dt.Quantity;
    reasonCode?: dt.CodeableConcept[];
    reasonReference?: dt.Reference[];
    relevantHistory?: dt.Reference[];
    replaces?: dt.Reference[];
    requester?: dt.Reference;
    requisition?: dt.Identifier;
    specimen?: dt.Reference[];
    status?: string;
    subject?: dt.Reference;
    supportingInfo?: dt.Reference[];
    text?: dt.Narrative;
    resourceType: string;
};
