import { b as dt } from "@openfn/language-fhir-4";
import type { builders as FHIR } from "@openfn/language-fhir-4";
export declare type Specimen_SzLabSpecimen_Props = {
    accessionIdentifier?: FHIR.Identifier;
    collection?: FHIR.BackboneElement;
    condition?: FHIR.CodeableConcept[];
    contained?: any[];
    container?: FHIR.BackboneElement[];
    extension?: FHIR.Extension[];
    id?: string;
    identifier?: FHIR.Identifier[];
    implicitRules?: string;
    language?: string;
    meta?: FHIR.Meta;
    modifierExtension?: FHIR.Extension[];
    note?: FHIR.Annotation[];
    parent?: FHIR.Reference[];
    processing?: FHIR.BackboneElement[];
    receivedTime?: string;
    request?: FHIR.Reference[];
    status?: string;
    subject?: FHIR.Reference;
    text?: FHIR.Narrative;
    type?: FHIR.CodeableConcept;
    [key: string]: any;
};
export default function (props: Partial<Specimen_SzLabSpecimen_Props>): {
    accessionIdentifier?: dt.Identifier;
    collection?: dt.BackboneElement;
    condition?: dt.CodeableConcept[];
    contained?: any[];
    container?: dt.BackboneElement[];
    extension?: dt.Extension[];
    id?: string;
    identifier?: dt.Identifier[];
    implicitRules?: string;
    language?: string;
    meta?: dt.Meta;
    modifierExtension?: dt.Extension[];
    note?: dt.Annotation[];
    parent?: dt.Reference[];
    processing?: dt.BackboneElement[];
    receivedTime?: string;
    request?: dt.Reference[];
    status?: string;
    subject?: dt.Reference;
    text?: dt.Narrative;
    type?: dt.CodeableConcept;
    resourceType: string;
};
