import { b as dt } from "@openfn/language-fhir-4";
import type { builders as FHIR } from "@openfn/language-fhir-4";
export declare type Location_SzLocation_Props = {
    address?: FHIR.Address;
    alias?: string[];
    availabilityExceptions?: string;
    contained?: any[];
    description?: string;
    endpoint?: FHIR.Reference[];
    extension?: FHIR.Extension[];
    hoursOfOperation?: FHIR.BackboneElement[];
    id?: string;
    identifier?: FHIR.Identifier[];
    implicitRules?: string;
    language?: string;
    managingOrganization?: FHIR.Reference;
    meta?: FHIR.Meta;
    mode?: string;
    modifierExtension?: FHIR.Extension[];
    name?: string;
    operationalStatus?: FHIR.Coding;
    partOf?: FHIR.Reference;
    physicalType?: FHIR.CodeableConcept;
    position?: FHIR.BackboneElement;
    status?: string;
    telecom?: FHIR.ContactPoint[];
    text?: FHIR.Narrative;
    type?: FHIR.CodeableConcept[];
    [key: string]: any;
};
export default function (props: Partial<Location_SzLocation_Props>): {
    address?: dt.Address;
    alias?: string[];
    availabilityExceptions?: string;
    contained?: any[];
    description?: string;
    endpoint?: dt.Reference[];
    extension?: dt.Extension[];
    hoursOfOperation?: dt.BackboneElement[];
    id?: string;
    identifier?: dt.Identifier[];
    implicitRules?: string;
    language?: string;
    managingOrganization?: dt.Reference;
    meta?: dt.Meta;
    mode?: string;
    modifierExtension?: dt.Extension[];
    name?: string;
    operationalStatus?: dt.Coding;
    partOf?: dt.Reference;
    physicalType?: dt.CodeableConcept;
    position?: dt.BackboneElement;
    status?: string;
    telecom?: dt.ContactPoint[];
    text?: dt.Narrative;
    type?: dt.CodeableConcept[];
    resourceType: string;
};
