import { b as dt } from "@openfn/language-fhir-4";
import type { builders as FHIR } from "@openfn/language-fhir-4";
export declare type Observation_SzMannerOfDeath_Props = {
    basedOn?: FHIR.Reference[];
    bodySite?: FHIR.CodeableConcept;
    category?: FHIR.CodeableConcept[];
    code?: FHIR.CodeableConcept;
    component?: FHIR.BackboneElement[];
    contained?: any[];
    dataAbsentReason?: FHIR.CodeableConcept;
    derivedFrom?: FHIR.Reference[];
    device?: FHIR.Reference;
    effective?: string | FHIR.Period | FHIR.Timing;
    encounter?: FHIR.Reference;
    extension?: FHIR.Extension[];
    focus?: FHIR.Reference[];
    hasMember?: FHIR.Reference[];
    id?: string;
    identifier?: FHIR.Identifier[];
    implicitRules?: string;
    interpretation?: FHIR.CodeableConcept[];
    issued?: string;
    language?: string;
    meta?: FHIR.Meta;
    method?: FHIR.CodeableConcept;
    modifierExtension?: FHIR.Extension[];
    note?: FHIR.Annotation[];
    partOf?: FHIR.Reference[];
    performer?: FHIR.Reference[];
    referenceRange?: FHIR.BackboneElement[];
    specimen?: FHIR.Reference;
    status?: string;
    subject?: FHIR.Reference;
    text?: FHIR.Narrative;
    value?: string;
    [key: string]: any;
};
export default function (props: Partial<Observation_SzMannerOfDeath_Props>): {
    basedOn?: dt.Reference[];
    bodySite?: dt.CodeableConcept;
    category?: dt.CodeableConcept[];
    code?: dt.CodeableConcept;
    component?: dt.BackboneElement[];
    contained?: any[];
    dataAbsentReason?: dt.CodeableConcept;
    derivedFrom?: dt.Reference[];
    device?: dt.Reference;
    effective?: string | dt.Period | dt.Timing;
    encounter?: dt.Reference;
    extension?: dt.Extension[];
    focus?: dt.Reference[];
    hasMember?: dt.Reference[];
    id?: string;
    identifier?: dt.Identifier[];
    implicitRules?: string;
    interpretation?: dt.CodeableConcept[];
    issued?: string;
    language?: string;
    meta?: dt.Meta;
    method?: dt.CodeableConcept;
    modifierExtension?: dt.Extension[];
    note?: dt.Annotation[];
    partOf?: dt.Reference[];
    performer?: dt.Reference[];
    referenceRange?: dt.BackboneElement[];
    specimen?: dt.Reference;
    status?: string;
    subject?: dt.Reference;
    text?: dt.Narrative;
    value?: string;
    resourceType: string;
};
