import { b as dt } from "@openfn/language-fhir-4";
import type { builders as FHIR } from "@openfn/language-fhir-4";
export declare type MedicationDispense_SzMedicationDispense_Props = {
    authorizingPrescription?: FHIR.Reference[];
    category?: FHIR.CodeableConcept;
    contained?: any[];
    context?: FHIR.Reference;
    daysSupply?: FHIR.Quantity;
    destination?: FHIR.Reference;
    detectedIssue?: FHIR.Reference[];
    dosageInstruction?: FHIR.Dosage[];
    eventHistory?: FHIR.Reference[];
    extension?: FHIR.Extension[];
    id?: string;
    identifier?: FHIR.Identifier[];
    implicitRules?: string;
    language?: string;
    location?: FHIR.Reference;
    medication?: FHIR.CodeableConcept;
    meta?: FHIR.Meta;
    modifierExtension?: FHIR.Extension[];
    note?: FHIR.Annotation[];
    partOf?: FHIR.Reference[];
    performer?: FHIR.BackboneElement[];
    quantity?: FHIR.Quantity;
    receiver?: FHIR.Reference[];
    status?: string;
    statusReason?: FHIR.CodeableConcept | FHIR.Reference;
    subject?: FHIR.Reference;
    substitution?: FHIR.BackboneElement;
    supportingInformation?: FHIR.Reference[];
    text?: FHIR.Narrative;
    type?: FHIR.CodeableConcept;
    whenHandedOver?: string;
    whenPrepared?: string;
    [key: string]: any;
};
export default function (props: Partial<MedicationDispense_SzMedicationDispense_Props>): {
    authorizingPrescription?: dt.Reference[];
    category?: dt.CodeableConcept;
    contained?: any[];
    context?: dt.Reference;
    daysSupply?: dt.Quantity;
    destination?: dt.Reference;
    detectedIssue?: dt.Reference[];
    dosageInstruction?: dt.Dosage[];
    eventHistory?: dt.Reference[];
    extension?: dt.Extension[];
    id?: string;
    identifier?: dt.Identifier[];
    implicitRules?: string;
    language?: string;
    location?: dt.Reference;
    medication?: dt.CodeableConcept;
    meta?: dt.Meta;
    modifierExtension?: dt.Extension[];
    note?: dt.Annotation[];
    partOf?: dt.Reference[];
    performer?: dt.BackboneElement[];
    quantity?: dt.Quantity;
    receiver?: dt.Reference[];
    status?: string;
    statusReason?: dt.CodeableConcept | dt.Reference;
    subject?: dt.Reference;
    substitution?: dt.BackboneElement;
    supportingInformation?: dt.Reference[];
    text?: dt.Narrative;
    type?: dt.CodeableConcept;
    whenHandedOver?: string;
    whenPrepared?: string;
    resourceType: string;
};
