import { b as dt } from "@openfn/language-fhir-4";
import type { builders as FHIR } from "@openfn/language-fhir-4";
export declare type MedicationRequest_SzMedicationRequest_Props = {
    authoredOn?: string;
    basedOn?: FHIR.Reference[];
    category?: FHIR.CodeableConcept[];
    contained?: any[];
    courseOfTherapyType?: FHIR.CodeableConcept;
    detectedIssue?: FHIR.Reference[];
    dispenseRequest?: FHIR.BackboneElement;
    doNotPerform?: boolean;
    dosageInstruction?: FHIR.Dosage[];
    encounter?: FHIR.Reference;
    eventHistory?: FHIR.Reference[];
    extension?: FHIR.Extension[];
    groupIdentifier?: FHIR.Identifier;
    id?: string;
    identifier?: FHIR.Identifier[];
    implicitRules?: string;
    instantiatesCanonical?: any[];
    instantiatesUri?: string[];
    insurance?: FHIR.Reference[];
    intent?: string;
    language?: string;
    medication?: FHIR.CodeableConcept;
    meta?: FHIR.Meta;
    modifierExtension?: FHIR.Extension[];
    note?: FHIR.Annotation[];
    performer?: FHIR.Reference;
    performerType?: FHIR.CodeableConcept;
    priorPrescription?: FHIR.Reference;
    priority?: string;
    reasonCode?: FHIR.CodeableConcept[];
    reasonReference?: FHIR.Reference[];
    recorder?: FHIR.Reference;
    reported?: boolean | FHIR.Reference;
    requester?: FHIR.Reference;
    status?: string;
    statusReason?: FHIR.CodeableConcept;
    subject?: FHIR.Reference;
    substitution?: FHIR.BackboneElement;
    supportingInformation?: FHIR.Reference[];
    text?: FHIR.Narrative;
    [key: string]: any;
};
export default function (props: Partial<MedicationRequest_SzMedicationRequest_Props>): {
    authoredOn?: string;
    basedOn?: dt.Reference[];
    category?: dt.CodeableConcept[];
    contained?: any[];
    courseOfTherapyType?: dt.CodeableConcept;
    detectedIssue?: dt.Reference[];
    dispenseRequest?: dt.BackboneElement;
    doNotPerform?: boolean;
    dosageInstruction?: dt.Dosage[];
    encounter?: dt.Reference;
    eventHistory?: dt.Reference[];
    extension?: dt.Extension[];
    groupIdentifier?: dt.Identifier;
    id?: string;
    identifier?: dt.Identifier[];
    implicitRules?: string;
    instantiatesCanonical?: any[];
    instantiatesUri?: string[];
    insurance?: dt.Reference[];
    intent?: string;
    language?: string;
    medication?: dt.CodeableConcept;
    meta?: dt.Meta;
    modifierExtension?: dt.Extension[];
    note?: dt.Annotation[];
    performer?: dt.Reference;
    performerType?: dt.CodeableConcept;
    priorPrescription?: dt.Reference;
    priority?: string;
    reasonCode?: dt.CodeableConcept[];
    reasonReference?: dt.Reference[];
    recorder?: dt.Reference;
    reported?: boolean | dt.Reference;
    requester?: dt.Reference;
    status?: string;
    statusReason?: dt.CodeableConcept;
    subject?: dt.Reference;
    substitution?: dt.BackboneElement;
    supportingInformation?: dt.Reference[];
    text?: dt.Narrative;
    resourceType: string;
};
