import { b as dt } from "@openfn/language-fhir-4";
import type { builders as FHIR } from "@openfn/language-fhir-4";
export declare type Medication_SzMedication_Props = {
    amount?: FHIR.Ratio;
    batch?: FHIR.BackboneElement;
    code?: FHIR.CodeableConcept;
    contained?: any[];
    extension?: FHIR.Extension[];
    form?: FHIR.CodeableConcept;
    id?: string;
    identifier?: FHIR.Identifier[];
    implicitRules?: string;
    ingredient?: FHIR.BackboneElement[];
    language?: string;
    manufacturer?: FHIR.Reference;
    meta?: FHIR.Meta;
    modifierExtension?: FHIR.Extension[];
    status?: string;
    text?: FHIR.Narrative;
    [key: string]: any;
};
export default function (props: Partial<Medication_SzMedication_Props>): {
    amount?: dt.Ratio;
    batch?: dt.BackboneElement;
    code?: dt.CodeableConcept;
    contained?: any[];
    extension?: dt.Extension[];
    form?: dt.CodeableConcept;
    id?: string;
    identifier?: dt.Identifier[];
    implicitRules?: string;
    ingredient?: dt.BackboneElement[];
    language?: string;
    manufacturer?: dt.Reference;
    meta?: dt.Meta;
    modifierExtension?: dt.Extension[];
    status?: string;
    text?: dt.Narrative;
    resourceType: string;
};
