import { b as dt } from "@openfn/language-fhir-4";
import type { builders as FHIR } from "@openfn/language-fhir-4";
export declare type Organization_SzOrganization_Props = {
    active?: boolean;
    address?: FHIR.Address[];
    alias?: string[];
    contact?: FHIR.BackboneElement[];
    contained?: any[];
    endpoint?: FHIR.Reference[];
    extension?: FHIR.Extension[];
    id?: string;
    identifier?: FHIR.Identifier[];
    implicitRules?: string;
    language?: string;
    meta?: FHIR.Meta;
    modifierExtension?: FHIR.Extension[];
    name?: string;
    partOf?: FHIR.Reference;
    telecom?: FHIR.ContactPoint[];
    text?: FHIR.Narrative;
    type?: FHIR.CodeableConcept[];
    [key: string]: any;
};
export default function (props: Partial<Organization_SzOrganization_Props>): {
    active?: boolean;
    address?: dt.Address[];
    alias?: string[];
    contact?: dt.BackboneElement[];
    contained?: any[];
    endpoint?: dt.Reference[];
    extension?: dt.Extension[];
    id?: string;
    identifier?: dt.Identifier[];
    implicitRules?: string;
    language?: string;
    meta?: dt.Meta;
    modifierExtension?: dt.Extension[];
    name?: string;
    partOf?: dt.Reference;
    telecom?: dt.ContactPoint[];
    text?: dt.Narrative;
    type?: dt.CodeableConcept[];
    resourceType: string;
};
