import { b as dt } from "@openfn/language-fhir-4";
import type { builders as FHIR } from "@openfn/language-fhir-4";
export declare type Practitioner_SzPractitioner_Props = {
    active?: boolean;
    address?: FHIR.Address[];
    birthDate?: string;
    communication?: FHIR.CodeableConcept[];
    contained?: any[];
    extension?: FHIR.Extension[];
    gender?: string;
    id?: string;
    identifier?: FHIR.Identifier[];
    implicitRules?: string;
    language?: string;
    meta?: FHIR.Meta;
    modifierExtension?: FHIR.Extension[];
    name?: FHIR.HumanName[];
    photo?: FHIR.Attachment[];
    qualification?: FHIR.BackboneElement[];
    telecom?: FHIR.ContactPoint[];
    text?: FHIR.Narrative;
    [key: string]: any;
};
export default function (props: Partial<Practitioner_SzPractitioner_Props>): {
    active?: boolean;
    address?: dt.Address[];
    birthDate?: string;
    communication?: dt.CodeableConcept[];
    contained?: any[];
    extension?: dt.Extension[];
    gender?: string;
    id?: string;
    identifier?: dt.Identifier[];
    implicitRules?: string;
    language?: string;
    meta?: dt.Meta;
    modifierExtension?: dt.Extension[];
    name?: dt.HumanName[];
    photo?: dt.Attachment[];
    qualification?: dt.BackboneElement[];
    telecom?: dt.ContactPoint[];
    text?: dt.Narrative;
    resourceType: string;
};
