import { b as dt } from "@openfn/language-fhir-4";
import type { builders as FHIR } from "@openfn/language-fhir-4";
export declare type Procedure_SzProcedure_Props = {
    asserter?: FHIR.Reference;
    basedOn?: FHIR.Reference[];
    bodySite?: FHIR.CodeableConcept[];
    category?: FHIR.CodeableConcept;
    code?: FHIR.CodeableConcept;
    complication?: FHIR.CodeableConcept[];
    complicationDetail?: FHIR.Reference[];
    contained?: any[];
    encounter?: FHIR.Reference;
    extension?: FHIR.Extension[];
    focalDevice?: FHIR.BackboneElement[];
    followUp?: FHIR.CodeableConcept[];
    id?: string;
    identifier?: FHIR.Identifier[];
    implicitRules?: string;
    instantiatesCanonical?: any[];
    instantiatesUri?: string[];
    language?: string;
    location?: FHIR.Reference;
    meta?: FHIR.Meta;
    modifierExtension?: FHIR.Extension[];
    note?: FHIR.Annotation[];
    outcome?: FHIR.CodeableConcept;
    partOf?: FHIR.Reference[];
    performed?: string | FHIR.Period | FHIR.Age | FHIR.Range;
    performer?: FHIR.BackboneElement[];
    reasonCode?: FHIR.CodeableConcept[];
    reasonReference?: FHIR.Reference[];
    recorder?: FHIR.Reference;
    report?: FHIR.Reference[];
    status?: string;
    statusReason?: FHIR.CodeableConcept;
    subject?: FHIR.Reference;
    text?: FHIR.Narrative;
    usedCode?: FHIR.CodeableConcept[];
    usedReference?: FHIR.Reference[];
    [key: string]: any;
};
export default function (props: Partial<Procedure_SzProcedure_Props>): {
    asserter?: dt.Reference;
    basedOn?: dt.Reference[];
    bodySite?: dt.CodeableConcept[];
    category?: dt.CodeableConcept;
    code?: dt.CodeableConcept;
    complication?: dt.CodeableConcept[];
    complicationDetail?: dt.Reference[];
    contained?: any[];
    encounter?: dt.Reference;
    extension?: dt.Extension[];
    focalDevice?: dt.BackboneElement[];
    followUp?: dt.CodeableConcept[];
    id?: string;
    identifier?: dt.Identifier[];
    implicitRules?: string;
    instantiatesCanonical?: any[];
    instantiatesUri?: string[];
    language?: string;
    location?: dt.Reference;
    meta?: dt.Meta;
    modifierExtension?: dt.Extension[];
    note?: dt.Annotation[];
    outcome?: dt.CodeableConcept;
    partOf?: dt.Reference[];
    performed?: string | dt.Period | dt.Age | dt.Range;
    performer?: dt.BackboneElement[];
    reasonCode?: dt.CodeableConcept[];
    reasonReference?: dt.Reference[];
    recorder?: dt.Reference;
    report?: dt.Reference[];
    status?: string;
    statusReason?: dt.CodeableConcept;
    subject?: dt.Reference;
    text?: dt.Narrative;
    usedCode?: dt.CodeableConcept[];
    usedReference?: dt.Reference[];
    resourceType: string;
};
