import * as dt from "../datatypes.js";
export declare type ActivityDefinition_Props = {
    id?: any;
    meta?: any;
    implicitRules?: any;
    language?: any;
    text?: any;
    contained?: any;
    extension?: any;
    modifierExtension?: any;
    url?: any;
    identifier?: dt.Identifier;
    version?: any;
    name?: any;
    title?: any;
    subtitle?: any;
    status?: any;
    experimental?: any;
    subject?: any;
    date?: any;
    publisher?: any;
    contact?: any;
    description?: any;
    useContext?: any;
    jurisdiction?: any;
    purpose?: any;
    usage?: any;
    copyright?: any;
    approvalDate?: any;
    lastReviewDate?: any;
    effectivePeriod?: any;
    topic?: any;
    author?: any;
    editor?: any;
    reviewer?: any;
    endorser?: any;
    relatedArtifact?: any;
    library?: any;
    kind?: any;
    profile?: any;
    code?: any;
    intent?: any;
    priority?: any;
    doNotPerform?: any;
    timing?: any;
    location?: any;
    participant?: any;
    product?: any;
    quantity?: any;
    dosage?: any;
    bodySite?: any;
    specimenRequirement?: any;
    observationRequirement?: any;
    observationResultRequirement?: any;
    transform?: any;
    dynamicValue?: any;
};
export default function (props: Partial<ActivityDefinition_Props>): {
    resourceType: string;
    text: {
        status: string;
        div: string;
    };
};
