import * as dt from "../datatypes.js";
export declare type CarePlan_Props = {
    id?: any;
    meta?: any;
    implicitRules?: any;
    language?: any;
    text?: any;
    contained?: any;
    extension?: any;
    modifierExtension?: any;
    identifier?: dt.Identifier;
    instantiatesCanonical?: any;
    instantiatesUri?: any;
    basedOn?: any;
    replaces?: any;
    partOf?: any;
    status?: any;
    intent?: any;
    category?: any;
    title?: any;
    description?: any;
    subject?: any;
    encounter?: any;
    period?: any;
    created?: any;
    author?: any;
    contributor?: any;
    careTeam?: any;
    addresses?: any;
    supportingInfo?: any;
    goal?: any;
    activity?: any;
    note?: any;
};
export default function (props: Partial<CarePlan_Props>): {
    resourceType: string;
    text: {
        status: string;
        div: string;
    };
};
