import * as dt from "../datatypes.js";
export declare type ChargeItemDefinition_Props = {
    id?: any;
    meta?: any;
    implicitRules?: any;
    language?: any;
    text?: any;
    contained?: any;
    extension?: any;
    modifierExtension?: any;
    url?: any;
    identifier?: dt.Identifier;
    version?: any;
    title?: any;
    derivedFromUri?: any;
    partOf?: any;
    replaces?: any;
    status?: any;
    experimental?: any;
    date?: any;
    publisher?: any;
    contact?: any;
    description?: any;
    useContext?: any;
    jurisdiction?: any;
    copyright?: any;
    approvalDate?: any;
    lastReviewDate?: any;
    effectivePeriod?: any;
    code?: any;
    instance?: any;
    applicability?: any;
    propertyGroup?: any;
};
export default function (props: Partial<ChargeItemDefinition_Props>): {
    resourceType: string;
    text: {
        status: string;
        div: string;
    };
};
