import * as dt from "../datatypes.js";
export declare type ChargeItem_Props = {
    id?: any;
    meta?: any;
    implicitRules?: any;
    language?: any;
    text?: any;
    contained?: any;
    extension?: any;
    modifierExtension?: any;
    identifier?: dt.Identifier;
    definitionUri?: any;
    definitionCanonical?: any;
    status?: any;
    partOf?: any;
    code?: any;
    subject?: any;
    context?: any;
    occurrence?: any;
    performer?: any;
    performingOrganization?: any;
    requestingOrganization?: any;
    costCenter?: any;
    quantity?: any;
    bodysite?: any;
    factorOverride?: any;
    priceOverride?: any;
    overrideReason?: any;
    enterer?: any;
    enteredDate?: any;
    reason?: any;
    service?: any;
    product?: any;
    account?: any;
    note?: any;
    supportingInformation?: any;
};
export default function (props: Partial<ChargeItem_Props>): {
    resourceType: string;
    text: {
        status: string;
        div: string;
    };
};
