import * as dt from "../datatypes.js";
export declare type Citation_Props = {
    id?: any;
    meta?: any;
    implicitRules?: any;
    language?: any;
    text?: any;
    contained?: any;
    extension?: any;
    modifierExtension?: any;
    url?: any;
    identifier?: dt.Identifier;
    version?: any;
    name?: any;
    title?: any;
    status?: any;
    experimental?: any;
    date?: any;
    publisher?: any;
    contact?: any;
    description?: any;
    useContext?: any;
    jurisdiction?: any;
    purpose?: any;
    copyright?: any;
    approvalDate?: any;
    lastReviewDate?: any;
    effectivePeriod?: any;
    author?: any;
    editor?: any;
    reviewer?: any;
    endorser?: any;
    summary?: any;
    classification?: any;
    note?: any;
    currentState?: any;
    statusDate?: any;
    relatesTo?: any;
    citedArtifact?: any;
};
export default function (props: Partial<Citation_Props>): {
    resourceType: string;
    text: {
        status: string;
        div: string;
    };
};
