import * as dt from "../datatypes.js";
export declare type ClaimResponse_Props = {
    id?: any;
    meta?: any;
    implicitRules?: any;
    language?: any;
    text?: any;
    contained?: any;
    extension?: any;
    modifierExtension?: any;
    identifier?: dt.Identifier;
    status?: any;
    type?: any;
    subType?: any;
    use?: any;
    patient?: any;
    created?: any;
    insurer?: any;
    requestor?: any;
    request?: any;
    outcome?: any;
    disposition?: any;
    preAuthRef?: any;
    preAuthPeriod?: any;
    payeeType?: any;
    item?: any;
    addItem?: any;
    adjudication?: any;
    total?: any;
    payment?: any;
    fundsReserve?: any;
    formCode?: any;
    form?: any;
    processNote?: any;
    communicationRequest?: any;
    insurance?: any;
    error?: any;
};
export default function (props: Partial<ClaimResponse_Props>): {
    resourceType: string;
    text: {
        status: string;
        div: string;
    };
};
