import * as dt from "../datatypes.js";
export declare type CommunicationRequest_Props = {
    id?: any;
    meta?: any;
    implicitRules?: any;
    language?: any;
    text?: any;
    contained?: any;
    extension?: any;
    modifierExtension?: any;
    identifier?: dt.Identifier;
    basedOn?: any;
    replaces?: any;
    groupIdentifier?: dt.Identifier;
    status?: any;
    statusReason?: any;
    category?: any;
    priority?: any;
    doNotPerform?: any;
    medium?: any;
    subject?: any;
    about?: any;
    encounter?: any;
    payload?: any;
    occurrence?: any;
    authoredOn?: any;
    requester?: any;
    recipient?: any;
    sender?: any;
    reasonCode?: any;
    reasonReference?: any;
    note?: any;
};
export default function (props: Partial<CommunicationRequest_Props>): {
    resourceType: string;
    text: {
        status: string;
        div: string;
    };
};
