import * as dt from "../datatypes.js";
export declare type Contract_Props = {
    id?: any;
    meta?: any;
    implicitRules?: any;
    language?: any;
    text?: any;
    contained?: any;
    extension?: any;
    modifierExtension?: any;
    identifier?: dt.Identifier;
    url?: any;
    version?: any;
    status?: any;
    legalState?: any;
    instantiatesCanonical?: any;
    instantiatesUri?: any;
    contentDerivative?: any;
    issued?: any;
    applies?: any;
    expirationType?: any;
    subject?: any;
    authority?: any;
    domain?: any;
    site?: any;
    name?: any;
    title?: any;
    subtitle?: any;
    alias?: any;
    author?: any;
    scope?: any;
    topic?: any;
    type?: any;
    subType?: any;
    contentDefinition?: any;
    term?: any;
    supportingInfo?: any;
    relevantHistory?: any;
    signer?: any;
    friendly?: any;
    legal?: any;
    rule?: any;
    legallyBinding?: any;
};
export default function (props: Partial<Contract_Props>): {
    resourceType: string;
    text: {
        status: string;
        div: string;
    };
};
