import * as dt from "../datatypes.js";
export declare type Device_Props = {
    id?: any;
    meta?: any;
    implicitRules?: any;
    language?: any;
    text?: any;
    contained?: any;
    extension?: any;
    modifierExtension?: any;
    identifier?: dt.Identifier;
    definition?: any;
    udiCarrier?: any;
    status?: any;
    statusReason?: any;
    distinctIdentifier?: any;
    manufacturer?: any;
    manufactureDate?: any;
    expirationDate?: any;
    lotNumber?: any;
    serialNumber?: any;
    deviceName?: any;
    modelNumber?: any;
    partNumber?: any;
    type?: any;
    specialization?: any;
    version?: any;
    property?: any;
    patient?: any;
    owner?: any;
    contact?: any;
    location?: any;
    url?: any;
    note?: any;
    safety?: any;
    parent?: any;
};
export default function (props: Partial<Device_Props>): {
    resourceType: string;
    text: {
        status: string;
        div: string;
    };
};
