import * as dt from "../datatypes.js";
export declare type Encounter_Props = {
    id?: any;
    meta?: any;
    implicitRules?: any;
    language?: any;
    text?: any;
    contained?: any;
    extension?: any;
    modifierExtension?: any;
    identifier?: dt.Identifier;
    status?: any;
    statusHistory?: any;
    class?: any;
    classHistory?: any;
    type?: any;
    serviceType?: any;
    priority?: any;
    subject?: any;
    episodeOfCare?: any;
    basedOn?: any;
    participant?: any;
    appointment?: any;
    period?: any;
    length?: any;
    reasonCode?: any;
    reasonReference?: any;
    diagnosis?: any;
    account?: any;
    hospitalization?: any;
    location?: any;
    serviceProvider?: any;
    partOf?: any;
};
export default function (props: Partial<Encounter_Props>): {
    resourceType: string;
    text: {
        status: string;
        div: string;
    };
};
