import * as dt from "../datatypes.js";
export declare type ExplanationOfBenefit_Props = {
    id?: any;
    meta?: any;
    implicitRules?: any;
    language?: any;
    text?: any;
    contained?: any;
    extension?: any;
    modifierExtension?: any;
    identifier?: dt.Identifier;
    status?: any;
    type?: any;
    subType?: any;
    use?: any;
    patient?: any;
    billablePeriod?: any;
    created?: any;
    enterer?: any;
    insurer?: any;
    provider?: any;
    priority?: any;
    fundsReserveRequested?: any;
    fundsReserve?: any;
    related?: any;
    prescription?: any;
    originalPrescription?: any;
    payee?: any;
    referral?: any;
    facility?: any;
    claim?: any;
    claimResponse?: any;
    outcome?: any;
    disposition?: any;
    preAuthRef?: any;
    preAuthRefPeriod?: any;
    careTeam?: any;
    supportingInfo?: any;
    diagnosis?: any;
    procedure?: any;
    precedence?: any;
    insurance?: any;
    accident?: any;
    item?: any;
    addItem?: any;
    adjudication?: any;
    total?: any;
    payment?: any;
    formCode?: any;
    form?: any;
    processNote?: any;
    benefitPeriod?: any;
    benefitBalance?: any;
};
export default function (props: Partial<ExplanationOfBenefit_Props>): {
    resourceType: string;
    text: {
        status: string;
        div: string;
    };
};
