import * as dt from "../datatypes.js";
export declare type MedicationDispense_Props = {
    id?: any;
    meta?: any;
    implicitRules?: any;
    language?: any;
    text?: any;
    contained?: any;
    extension?: any;
    modifierExtension?: any;
    identifier?: dt.Identifier;
    partOf?: any;
    status?: any;
    statusReason?: any;
    category?: any;
    medication?: any;
    subject?: any;
    context?: any;
    supportingInformation?: any;
    performer?: any;
    location?: any;
    authorizingPrescription?: any;
    type?: any;
    quantity?: any;
    daysSupply?: any;
    whenPrepared?: any;
    whenHandedOver?: any;
    destination?: any;
    receiver?: any;
    note?: any;
    dosageInstruction?: any;
    substitution?: any;
    detectedIssue?: any;
    eventHistory?: any;
};
export default function (props: Partial<MedicationDispense_Props>): {
    resourceType: string;
    text: {
        status: string;
        div: string;
    };
};
