import * as dt from "../datatypes.js";
export declare type Media_Props = {
    id?: any;
    meta?: any;
    implicitRules?: any;
    language?: any;
    text?: any;
    contained?: any;
    extension?: any;
    modifierExtension?: any;
    identifier?: dt.Identifier;
    basedOn?: any;
    partOf?: any;
    status?: any;
    type?: any;
    modality?: any;
    view?: any;
    subject?: any;
    encounter?: any;
    created?: any;
    issued?: any;
    operator?: any;
    reasonCode?: any;
    bodySite?: any;
    deviceName?: any;
    device?: any;
    height?: any;
    width?: any;
    frames?: any;
    duration?: any;
    content?: any;
    note?: any;
};
export default function (props: Partial<Media_Props>): {
    resourceType: string;
    text: {
        status: string;
        div: string;
    };
};
