import * as dt from "../datatypes.js";
export declare type MedicinalProductDefinition_Props = {
    id?: any;
    meta?: any;
    implicitRules?: any;
    language?: any;
    text?: any;
    contained?: any;
    extension?: any;
    modifierExtension?: any;
    identifier?: dt.Identifier;
    type?: any;
    domain?: any;
    version?: any;
    status?: any;
    statusDate?: any;
    description?: any;
    combinedPharmaceuticalDoseForm?: any;
    route?: any;
    indication?: any;
    legalStatusOfSupply?: any;
    additionalMonitoringIndicator?: any;
    specialMeasures?: any;
    pediatricUseIndicator?: any;
    classification?: any;
    marketingStatus?: any;
    packagedMedicinalProduct?: any;
    ingredient?: any;
    impurity?: any;
    attachedDocument?: any;
    masterFile?: any;
    contact?: any;
    clinicalTrial?: any;
    code?: any;
    name?: any;
    crossReference?: any;
    operation?: any;
    characteristic?: any;
};
export default function (props: Partial<MedicinalProductDefinition_Props>): {
    resourceType: string;
    text: {
        status: string;
        div: string;
    };
};
