import * as dt from "../datatypes.js";
export declare type MedicationRequest_Props = {
    id?: any;
    meta?: any;
    implicitRules?: any;
    language?: any;
    text?: any;
    contained?: any;
    extension?: any;
    modifierExtension?: any;
    identifier?: dt.Identifier;
    status?: any;
    statusReason?: any;
    intent?: any;
    category?: any;
    priority?: any;
    doNotPerform?: any;
    reported?: any;
    medication?: any;
    subject?: any;
    encounter?: any;
    supportingInformation?: any;
    authoredOn?: any;
    requester?: any;
    performer?: any;
    performerType?: any;
    recorder?: any;
    reasonCode?: any;
    reasonReference?: any;
    instantiatesCanonical?: any;
    instantiatesUri?: any;
    basedOn?: any;
    groupIdentifier?: dt.Identifier;
    courseOfTherapyType?: any;
    insurance?: any;
    note?: any;
    dosageInstruction?: any;
    dispenseRequest?: any;
    substitution?: any;
    priorPrescription?: any;
    detectedIssue?: any;
    eventHistory?: any;
};
export default function (props: Partial<MedicationRequest_Props>): {
    resourceType: string;
    text: {
        status: string;
        div: string;
    };
};
