import * as dt from "../datatypes.js";
export declare type ResearchStudy_Props = {
    id?: any;
    meta?: any;
    implicitRules?: any;
    language?: any;
    text?: any;
    contained?: any;
    extension?: any;
    modifierExtension?: any;
    identifier?: dt.Identifier;
    title?: any;
    protocol?: any;
    partOf?: any;
    status?: any;
    primaryPurposeType?: any;
    phase?: any;
    category?: any;
    focus?: any;
    condition?: any;
    contact?: any;
    relatedArtifact?: any;
    keyword?: any;
    location?: any;
    description?: any;
    enrollment?: any;
    period?: any;
    sponsor?: any;
    principalInvestigator?: any;
    site?: any;
    reasonStopped?: any;
    note?: any;
    arm?: any;
    objective?: any;
};
export default function (props: Partial<ResearchStudy_Props>): {
    resourceType: string;
    text: {
        status: string;
        div: string;
    };
};
