import * as dt from "../datatypes.js";
export declare type ServiceRequest_Props = {
    id?: any;
    meta?: any;
    implicitRules?: any;
    language?: any;
    text?: any;
    contained?: any;
    extension?: any;
    modifierExtension?: any;
    identifier?: dt.Identifier;
    instantiatesCanonical?: any;
    instantiatesUri?: any;
    basedOn?: any;
    replaces?: any;
    requisition?: dt.Identifier;
    status?: any;
    intent?: any;
    category?: any;
    priority?: any;
    doNotPerform?: any;
    code?: any;
    orderDetail?: any;
    quantity?: any;
    subject?: any;
    encounter?: any;
    occurrence?: any;
    asNeeded?: any;
    authoredOn?: any;
    requester?: any;
    performerType?: any;
    performer?: any;
    locationCode?: any;
    locationReference?: any;
    reasonCode?: any;
    reasonReference?: any;
    insurance?: any;
    supportingInfo?: any;
    specimen?: any;
    bodySite?: any;
    note?: any;
    patientInstruction?: any;
    relevantHistory?: any;
};
export default function (props: Partial<ServiceRequest_Props>): {
    resourceType: string;
    text: {
        status: string;
        div: string;
    };
};
