import * as dt from "../datatypes.js";
export declare type Task_Props = {
    id?: any;
    meta?: any;
    implicitRules?: any;
    language?: any;
    text?: any;
    contained?: any;
    extension?: any;
    modifierExtension?: any;
    identifier?: dt.Identifier;
    instantiatesCanonical?: any;
    instantiatesUri?: any;
    basedOn?: any;
    groupIdentifier?: dt.Identifier;
    partOf?: any;
    status?: any;
    statusReason?: any;
    businessStatus?: any;
    intent?: any;
    priority?: any;
    code?: any;
    description?: any;
    focus?: any;
    for?: any;
    encounter?: any;
    executionPeriod?: any;
    authoredOn?: any;
    lastModified?: any;
    requester?: any;
    performerType?: any;
    owner?: any;
    location?: any;
    reasonCode?: any;
    reasonReference?: any;
    insurance?: any;
    note?: any;
    relevantHistory?: any;
    restriction?: any;
    input?: any;
    output?: any;
};
export default function (props: Partial<Task_Props>): {
    resourceType: string;
    text: {
        status: string;
        div: string;
    };
};
