import * as dt from "../datatypes.js";
export declare type TestScript_Props = {
    id?: any;
    meta?: any;
    implicitRules?: any;
    language?: any;
    text?: any;
    contained?: any;
    extension?: any;
    modifierExtension?: any;
    url?: any;
    identifier?: dt.Identifier;
    version?: any;
    name?: any;
    title?: any;
    status?: any;
    experimental?: any;
    date?: any;
    publisher?: any;
    contact?: any;
    description?: any;
    useContext?: any;
    jurisdiction?: any;
    purpose?: any;
    copyright?: any;
    origin?: any;
    destination?: any;
    metadata?: any;
    fixture?: any;
    profile?: any;
    variable?: any;
    setup?: any;
    test?: any;
    teardown?: any;
};
export default function (props: Partial<TestScript_Props>): {
    resourceType: string;
    text: {
        status: string;
        div: string;
    };
};
