import { b as dt } from "@openfn/language-fhir-4";
import type { builders as FHIR } from "@openfn/language-fhir-4";
export declare type Patient_Props = {
    active?: boolean;
    address?: FHIR.Address[];
    birthDate?: string;
    communication?: FHIR.BackboneElement[];
    contact?: FHIR.BackboneElement[];
    contained?: any[];
    deceased?: boolean | string;
    extension?: FHIR.Extension[];
    gender?: string;
    generalPractitioner?: FHIR.Reference[];
    id?: string;
    identifier?: FHIR.Identifier[];
    implicitRules?: string;
    language?: string;
    link?: FHIR.BackboneElement[];
    managingOrganization?: FHIR.Reference;
    maritalStatus?: FHIR.CodeableConcept;
    meta?: FHIR.Meta;
    modifierExtension?: FHIR.Extension[];
    multipleBirth?: boolean | number;
    name?: FHIR.HumanName[];
    photo?: FHIR.Attachment[];
    telecom?: FHIR.ContactPoint[];
    text?: FHIR.Narrative;
    [key: string]: any;
};
export default function (props: Partial<Patient_Props>): {
    active?: boolean;
    address?: dt.Address[];
    birthDate?: string;
    communication?: dt.BackboneElement[];
    contact?: dt.BackboneElement[];
    contained?: any[];
    deceased?: string | boolean;
    extension?: dt.Extension[];
    gender?: string;
    generalPractitioner?: dt.Reference[];
    id?: string;
    identifier?: dt.Identifier[];
    implicitRules?: string;
    language?: string;
    link?: dt.BackboneElement[];
    managingOrganization?: dt.Reference;
    maritalStatus?: dt.CodeableConcept;
    meta?: dt.Meta;
    modifierExtension?: dt.Extension[];
    multipleBirth?: number | boolean;
    name?: dt.HumanName[];
    photo?: dt.Attachment[];
    telecom?: dt.ContactPoint[];
    text?: dt.Narrative;
    resourceType: string;
};
