import { Account_Props } from "./profiles/Account";
import { ActivityDefinition_Props } from "./profiles/ActivityDefinition";
import { AdministrableProductDefinition_Props } from "./profiles/AdministrableProductDefinition";
import { AdverseEvent_Props } from "./profiles/AdverseEvent";
import { AllergyIntolerance_Props } from "./profiles/AllergyIntolerance";
import { Appointment_Props } from "./profiles/Appointment";
import { AppointmentResponse_Props } from "./profiles/AppointmentResponse";
import { BiologicallyDerivedProduct_Props } from "./profiles/BiologicallyDerivedProduct";
import { BodyStructure_Props } from "./profiles/BodyStructure";
import { CarePlan_Props } from "./profiles/CarePlan";
import { CareTeam_Props } from "./profiles/CareTeam";
import { ChargeItem_Props } from "./profiles/ChargeItem";
import { ChargeItemDefinition_Props } from "./profiles/ChargeItemDefinition";
import { Citation_Props } from "./profiles/Citation";
import { Claim_Props } from "./profiles/Claim";
import { ClaimResponse_Props } from "./profiles/ClaimResponse";
import { ClinicalImpression_Props } from "./profiles/ClinicalImpression";
import { ClinicalUseDefinition_Props } from "./profiles/ClinicalUseDefinition";
import { Communication_Props } from "./profiles/Communication";
import { CommunicationRequest_Props } from "./profiles/CommunicationRequest";
import { Condition_Props } from "./profiles/Condition";
import { Contract_Props } from "./profiles/Contract";
import { Coverage_Props } from "./profiles/Coverage";
import { CoverageEligibilityRequest_Props } from "./profiles/CoverageEligibilityRequest";
import { CoverageEligibilityResponse_Props } from "./profiles/CoverageEligibilityResponse";
import { DetectedIssue_Props } from "./profiles/DetectedIssue";
import { Device_Props } from "./profiles/Device";
import { DeviceDefinition_Props } from "./profiles/DeviceDefinition";
import { DeviceMetric_Props } from "./profiles/DeviceMetric";
import { DeviceRequest_Props } from "./profiles/DeviceRequest";
import { DeviceUseStatement_Props } from "./profiles/DeviceUseStatement";
import { DiagnosticReport_Props } from "./profiles/DiagnosticReport";
import { DomainResource_Props } from "./profiles/DomainResource";
import { Encounter_Props } from "./profiles/Encounter";
import { Endpoint_Props } from "./profiles/Endpoint";
import { EnrollmentRequest_Props } from "./profiles/EnrollmentRequest";
import { EnrollmentResponse_Props } from "./profiles/EnrollmentResponse";
import { EpisodeOfCare_Props } from "./profiles/EpisodeOfCare";
import { EventDefinition_Props } from "./profiles/EventDefinition";
import { Evidence_Props } from "./profiles/Evidence";
import { EvidenceReport_Props } from "./profiles/EvidenceReport";
import { EvidenceVariable_Props } from "./profiles/EvidenceVariable";
import { ExplanationOfBenefit_Props } from "./profiles/ExplanationOfBenefit";
import { FamilyMemberHistory_Props } from "./profiles/FamilyMemberHistory";
import { Flag_Props } from "./profiles/Flag";
import { Goal_Props } from "./profiles/Goal";
import { Group_Props } from "./profiles/Group";
import { GuidanceResponse_Props } from "./profiles/GuidanceResponse";
import { HealthcareService_Props } from "./profiles/HealthcareService";
import { ImagingStudy_Props } from "./profiles/ImagingStudy";
import { Immunization_Props } from "./profiles/Immunization";
import { ImmunizationEvaluation_Props } from "./profiles/ImmunizationEvaluation";
import { ImmunizationRecommendation_Props } from "./profiles/ImmunizationRecommendation";
import { Ingredient_Props } from "./profiles/Ingredient";
import { InsurancePlan_Props } from "./profiles/InsurancePlan";
import { Invoice_Props } from "./profiles/Invoice";
import { Library_Props } from "./profiles/Library";
import { List_Props } from "./profiles/List";
import { Location_Props } from "./profiles/Location";
import { ManufacturedItemDefinition_Props } from "./profiles/ManufacturedItemDefinition";
import { Measure_Props } from "./profiles/Measure";
import { MeasureReport_Props } from "./profiles/MeasureReport";
import { Media_Props } from "./profiles/Media";
import { Medication_Props } from "./profiles/Medication";
import { MedicationAdministration_Props } from "./profiles/MedicationAdministration";
import { MedicationDispense_Props } from "./profiles/MedicationDispense";
import { MedicationKnowledge_Props } from "./profiles/MedicationKnowledge";
import { MedicationRequest_Props } from "./profiles/MedicationRequest";
import { MedicationStatement_Props } from "./profiles/MedicationStatement";
import { MedicinalProductDefinition_Props } from "./profiles/MedicinalProductDefinition";
import { MolecularSequence_Props } from "./profiles/MolecularSequence";
import { NutritionOrder_Props } from "./profiles/NutritionOrder";
import { NutritionProduct_Props } from "./profiles/NutritionProduct";
import { Observation_Props } from "./profiles/Observation";
import { ObservationDefinition_Props } from "./profiles/ObservationDefinition";
import { Organization_Props } from "./profiles/Organization";
import { OrganizationAffiliation_Props } from "./profiles/OrganizationAffiliation";
import { PackagedProductDefinition_Props } from "./profiles/PackagedProductDefinition";
import { Patient_Props } from "./profiles/Patient";
import { PaymentNotice_Props } from "./profiles/PaymentNotice";
import { PaymentReconciliation_Props } from "./profiles/PaymentReconciliation";
import { Person_Props } from "./profiles/Person";
import { PlanDefinition_Props } from "./profiles/PlanDefinition";
import { Practitioner_Props } from "./profiles/Practitioner";
import { PractitionerRole_Props } from "./profiles/PractitionerRole";
import { Procedure_Props } from "./profiles/Procedure";
import { Questionnaire_Props } from "./profiles/Questionnaire";
import { QuestionnaireResponse_Props } from "./profiles/QuestionnaireResponse";
import { RegulatedAuthorization_Props } from "./profiles/RegulatedAuthorization";
import { RelatedPerson_Props } from "./profiles/RelatedPerson";
import { RequestGroup_Props } from "./profiles/RequestGroup";
import { ResearchDefinition_Props } from "./profiles/ResearchDefinition";
import { ResearchElementDefinition_Props } from "./profiles/ResearchElementDefinition";
import { ResearchStudy_Props } from "./profiles/ResearchStudy";
import { ResearchSubject_Props } from "./profiles/ResearchSubject";
import { Resource_Props } from "./profiles/Resource";
import { RiskAssessment_Props } from "./profiles/RiskAssessment";
import { Schedule_Props } from "./profiles/Schedule";
import { ServiceRequest_Props } from "./profiles/ServiceRequest";
import { Slot_Props } from "./profiles/Slot";
import { Specimen_Props } from "./profiles/Specimen";
import { SpecimenDefinition_Props } from "./profiles/SpecimenDefinition";
import { Substance_Props } from "./profiles/Substance";
import { SubstanceDefinition_Props } from "./profiles/SubstanceDefinition";
import { SupplyDelivery_Props } from "./profiles/SupplyDelivery";
import { SupplyRequest_Props } from "./profiles/SupplyRequest";
import { Task_Props } from "./profiles/Task";
import { TestReport_Props } from "./profiles/TestReport";
import { TestScript_Props } from "./profiles/TestScript";
import { VerificationResult_Props } from "./profiles/VerificationResult";
import { VisionPrescription_Props } from "./profiles/VisionPrescription";
export declare function account(type: string, props: Account_Props): any;
export declare function account(props: Account_Props): any;
export declare function activityDefinition(type: string, props: ActivityDefinition_Props): any;
export declare function activityDefinition(props: ActivityDefinition_Props): any;
export declare function administrableProductDefinition(type: string, props: AdministrableProductDefinition_Props): any;
export declare function administrableProductDefinition(props: AdministrableProductDefinition_Props): any;
export declare function adverseEvent(type: string, props: AdverseEvent_Props): any;
export declare function adverseEvent(props: AdverseEvent_Props): any;
export declare function allergyIntolerance(type: string, props: AllergyIntolerance_Props): any;
export declare function allergyIntolerance(props: AllergyIntolerance_Props): any;
export declare function appointment(type: string, props: Appointment_Props): any;
export declare function appointment(props: Appointment_Props): any;
export declare function appointmentResponse(type: string, props: AppointmentResponse_Props): any;
export declare function appointmentResponse(props: AppointmentResponse_Props): any;
export declare function biologicallyDerivedProduct(type: string, props: BiologicallyDerivedProduct_Props): any;
export declare function biologicallyDerivedProduct(props: BiologicallyDerivedProduct_Props): any;
export declare function bodyStructure(type: string, props: BodyStructure_Props): any;
export declare function bodyStructure(props: BodyStructure_Props): any;
export declare function carePlan(type: string, props: CarePlan_Props): any;
export declare function carePlan(props: CarePlan_Props): any;
export declare function careTeam(type: string, props: CareTeam_Props): any;
export declare function careTeam(props: CareTeam_Props): any;
export declare function chargeItem(type: string, props: ChargeItem_Props): any;
export declare function chargeItem(props: ChargeItem_Props): any;
export declare function chargeItemDefinition(type: string, props: ChargeItemDefinition_Props): any;
export declare function chargeItemDefinition(props: ChargeItemDefinition_Props): any;
export declare function citation(type: string, props: Citation_Props): any;
export declare function citation(props: Citation_Props): any;
export declare function claim(type: string, props: Claim_Props): any;
export declare function claim(props: Claim_Props): any;
export declare function claimResponse(type: string, props: ClaimResponse_Props): any;
export declare function claimResponse(props: ClaimResponse_Props): any;
export declare function clinicalImpression(type: string, props: ClinicalImpression_Props): any;
export declare function clinicalImpression(props: ClinicalImpression_Props): any;
export declare function clinicalUseDefinition(type: string, props: ClinicalUseDefinition_Props): any;
export declare function clinicalUseDefinition(props: ClinicalUseDefinition_Props): any;
export declare function communication(type: string, props: Communication_Props): any;
export declare function communication(props: Communication_Props): any;
export declare function communicationRequest(type: string, props: CommunicationRequest_Props): any;
export declare function communicationRequest(props: CommunicationRequest_Props): any;
export declare function condition(type: string, props: Condition_Props): any;
export declare function condition(props: Condition_Props): any;
export declare function contract(type: string, props: Contract_Props): any;
export declare function contract(props: Contract_Props): any;
export declare function coverage(type: string, props: Coverage_Props): any;
export declare function coverage(props: Coverage_Props): any;
export declare function coverageEligibilityRequest(type: string, props: CoverageEligibilityRequest_Props): any;
export declare function coverageEligibilityRequest(props: CoverageEligibilityRequest_Props): any;
export declare function coverageEligibilityResponse(type: string, props: CoverageEligibilityResponse_Props): any;
export declare function coverageEligibilityResponse(props: CoverageEligibilityResponse_Props): any;
export declare function detectedIssue(type: string, props: DetectedIssue_Props): any;
export declare function detectedIssue(props: DetectedIssue_Props): any;
export declare function device(type: string, props: Device_Props): any;
export declare function device(props: Device_Props): any;
export declare function deviceDefinition(type: string, props: DeviceDefinition_Props): any;
export declare function deviceDefinition(props: DeviceDefinition_Props): any;
export declare function deviceMetric(type: string, props: DeviceMetric_Props): any;
export declare function deviceMetric(props: DeviceMetric_Props): any;
export declare function deviceRequest(type: string, props: DeviceRequest_Props): any;
export declare function deviceRequest(props: DeviceRequest_Props): any;
export declare function deviceUseStatement(type: string, props: DeviceUseStatement_Props): any;
export declare function deviceUseStatement(props: DeviceUseStatement_Props): any;
export declare function diagnosticReport(type: string, props: DiagnosticReport_Props): any;
export declare function diagnosticReport(props: DiagnosticReport_Props): any;
export declare function domainResource(type: string, props: DomainResource_Props): any;
export declare function domainResource(props: DomainResource_Props): any;
export declare function encounter(type: string, props: Encounter_Props): any;
export declare function encounter(props: Encounter_Props): any;
export declare function endpoint(type: string, props: Endpoint_Props): any;
export declare function endpoint(props: Endpoint_Props): any;
export declare function enrollmentRequest(type: string, props: EnrollmentRequest_Props): any;
export declare function enrollmentRequest(props: EnrollmentRequest_Props): any;
export declare function enrollmentResponse(type: string, props: EnrollmentResponse_Props): any;
export declare function enrollmentResponse(props: EnrollmentResponse_Props): any;
export declare function episodeOfCare(type: string, props: EpisodeOfCare_Props): any;
export declare function episodeOfCare(props: EpisodeOfCare_Props): any;
export declare function eventDefinition(type: string, props: EventDefinition_Props): any;
export declare function eventDefinition(props: EventDefinition_Props): any;
export declare function evidence(type: string, props: Evidence_Props): any;
export declare function evidence(props: Evidence_Props): any;
export declare function evidenceReport(type: string, props: EvidenceReport_Props): any;
export declare function evidenceReport(props: EvidenceReport_Props): any;
export declare function evidenceVariable(type: string, props: EvidenceVariable_Props): any;
export declare function evidenceVariable(props: EvidenceVariable_Props): any;
export declare function explanationOfBenefit(type: string, props: ExplanationOfBenefit_Props): any;
export declare function explanationOfBenefit(props: ExplanationOfBenefit_Props): any;
export declare function familyMemberHistory(type: string, props: FamilyMemberHistory_Props): any;
export declare function familyMemberHistory(props: FamilyMemberHistory_Props): any;
export declare function flag(type: string, props: Flag_Props): any;
export declare function flag(props: Flag_Props): any;
export declare function goal(type: string, props: Goal_Props): any;
export declare function goal(props: Goal_Props): any;
export declare function group(type: string, props: Group_Props): any;
export declare function group(props: Group_Props): any;
export declare function guidanceResponse(type: string, props: GuidanceResponse_Props): any;
export declare function guidanceResponse(props: GuidanceResponse_Props): any;
export declare function healthcareService(type: string, props: HealthcareService_Props): any;
export declare function healthcareService(props: HealthcareService_Props): any;
export declare function imagingStudy(type: string, props: ImagingStudy_Props): any;
export declare function imagingStudy(props: ImagingStudy_Props): any;
export declare function immunization(type: string, props: Immunization_Props): any;
export declare function immunization(props: Immunization_Props): any;
export declare function immunizationEvaluation(type: string, props: ImmunizationEvaluation_Props): any;
export declare function immunizationEvaluation(props: ImmunizationEvaluation_Props): any;
export declare function immunizationRecommendation(type: string, props: ImmunizationRecommendation_Props): any;
export declare function immunizationRecommendation(props: ImmunizationRecommendation_Props): any;
export declare function ingredient(type: string, props: Ingredient_Props): any;
export declare function ingredient(props: Ingredient_Props): any;
export declare function insurancePlan(type: string, props: InsurancePlan_Props): any;
export declare function insurancePlan(props: InsurancePlan_Props): any;
export declare function invoice(type: string, props: Invoice_Props): any;
export declare function invoice(props: Invoice_Props): any;
export declare function library(type: string, props: Library_Props): any;
export declare function library(props: Library_Props): any;
export declare function list(type: string, props: List_Props): any;
export declare function list(props: List_Props): any;
export declare function location(type: string, props: Location_Props): any;
export declare function location(props: Location_Props): any;
export declare function manufacturedItemDefinition(type: string, props: ManufacturedItemDefinition_Props): any;
export declare function manufacturedItemDefinition(props: ManufacturedItemDefinition_Props): any;
export declare function measure(type: string, props: Measure_Props): any;
export declare function measure(props: Measure_Props): any;
export declare function measureReport(type: string, props: MeasureReport_Props): any;
export declare function measureReport(props: MeasureReport_Props): any;
export declare function media(type: string, props: Media_Props): any;
export declare function media(props: Media_Props): any;
export declare function medication(type: string, props: Medication_Props): any;
export declare function medication(props: Medication_Props): any;
export declare function medicationAdministration(type: string, props: MedicationAdministration_Props): any;
export declare function medicationAdministration(props: MedicationAdministration_Props): any;
export declare function medicationDispense(type: string, props: MedicationDispense_Props): any;
export declare function medicationDispense(props: MedicationDispense_Props): any;
export declare function medicationKnowledge(type: string, props: MedicationKnowledge_Props): any;
export declare function medicationKnowledge(props: MedicationKnowledge_Props): any;
export declare function medicationRequest(type: string, props: MedicationRequest_Props): any;
export declare function medicationRequest(props: MedicationRequest_Props): any;
export declare function medicationStatement(type: string, props: MedicationStatement_Props): any;
export declare function medicationStatement(props: MedicationStatement_Props): any;
export declare function medicinalProductDefinition(type: string, props: MedicinalProductDefinition_Props): any;
export declare function medicinalProductDefinition(props: MedicinalProductDefinition_Props): any;
export declare function molecularSequence(type: string, props: MolecularSequence_Props): any;
export declare function molecularSequence(props: MolecularSequence_Props): any;
export declare function nutritionOrder(type: string, props: NutritionOrder_Props): any;
export declare function nutritionOrder(props: NutritionOrder_Props): any;
export declare function nutritionProduct(type: string, props: NutritionProduct_Props): any;
export declare function nutritionProduct(props: NutritionProduct_Props): any;
export declare function observation(type: string, props: Observation_Props): any;
export declare function observation(props: Observation_Props): any;
export declare function observationDefinition(type: string, props: ObservationDefinition_Props): any;
export declare function observationDefinition(props: ObservationDefinition_Props): any;
export declare function organization(type: string, props: Organization_Props): any;
export declare function organization(props: Organization_Props): any;
export declare function organizationAffiliation(type: string, props: OrganizationAffiliation_Props): any;
export declare function organizationAffiliation(props: OrganizationAffiliation_Props): any;
export declare function packagedProductDefinition(type: string, props: PackagedProductDefinition_Props): any;
export declare function packagedProductDefinition(props: PackagedProductDefinition_Props): any;
export declare function patient(type: string, props: Patient_Props): any;
export declare function patient(props: Patient_Props): any;
export declare function paymentNotice(type: string, props: PaymentNotice_Props): any;
export declare function paymentNotice(props: PaymentNotice_Props): any;
export declare function paymentReconciliation(type: string, props: PaymentReconciliation_Props): any;
export declare function paymentReconciliation(props: PaymentReconciliation_Props): any;
export declare function person(type: string, props: Person_Props): any;
export declare function person(props: Person_Props): any;
export declare function planDefinition(type: string, props: PlanDefinition_Props): any;
export declare function planDefinition(props: PlanDefinition_Props): any;
export declare function practitioner(type: string, props: Practitioner_Props): any;
export declare function practitioner(props: Practitioner_Props): any;
export declare function practitionerRole(type: string, props: PractitionerRole_Props): any;
export declare function practitionerRole(props: PractitionerRole_Props): any;
export declare function procedure(type: string, props: Procedure_Props): any;
export declare function procedure(props: Procedure_Props): any;
export declare function questionnaire(type: string, props: Questionnaire_Props): any;
export declare function questionnaire(props: Questionnaire_Props): any;
export declare function questionnaireResponse(type: string, props: QuestionnaireResponse_Props): any;
export declare function questionnaireResponse(props: QuestionnaireResponse_Props): any;
export declare function regulatedAuthorization(type: string, props: RegulatedAuthorization_Props): any;
export declare function regulatedAuthorization(props: RegulatedAuthorization_Props): any;
export declare function relatedPerson(type: string, props: RelatedPerson_Props): any;
export declare function relatedPerson(props: RelatedPerson_Props): any;
export declare function requestGroup(type: string, props: RequestGroup_Props): any;
export declare function requestGroup(props: RequestGroup_Props): any;
export declare function researchDefinition(type: string, props: ResearchDefinition_Props): any;
export declare function researchDefinition(props: ResearchDefinition_Props): any;
export declare function researchElementDefinition(type: string, props: ResearchElementDefinition_Props): any;
export declare function researchElementDefinition(props: ResearchElementDefinition_Props): any;
export declare function researchStudy(type: string, props: ResearchStudy_Props): any;
export declare function researchStudy(props: ResearchStudy_Props): any;
export declare function researchSubject(type: string, props: ResearchSubject_Props): any;
export declare function researchSubject(props: ResearchSubject_Props): any;
export declare function resource(type: string, props: Resource_Props): any;
export declare function resource(props: Resource_Props): any;
export declare function riskAssessment(type: string, props: RiskAssessment_Props): any;
export declare function riskAssessment(props: RiskAssessment_Props): any;
export declare function schedule(type: string, props: Schedule_Props): any;
export declare function schedule(props: Schedule_Props): any;
export declare function serviceRequest(type: string, props: ServiceRequest_Props): any;
export declare function serviceRequest(props: ServiceRequest_Props): any;
export declare function slot(type: string, props: Slot_Props): any;
export declare function slot(props: Slot_Props): any;
export declare function specimen(type: string, props: Specimen_Props): any;
export declare function specimen(props: Specimen_Props): any;
export declare function specimenDefinition(type: string, props: SpecimenDefinition_Props): any;
export declare function specimenDefinition(props: SpecimenDefinition_Props): any;
export declare function substance(type: string, props: Substance_Props): any;
export declare function substance(props: Substance_Props): any;
export declare function substanceDefinition(type: string, props: SubstanceDefinition_Props): any;
export declare function substanceDefinition(props: SubstanceDefinition_Props): any;
export declare function supplyDelivery(type: string, props: SupplyDelivery_Props): any;
export declare function supplyDelivery(props: SupplyDelivery_Props): any;
export declare function supplyRequest(type: string, props: SupplyRequest_Props): any;
export declare function supplyRequest(props: SupplyRequest_Props): any;
export declare function task(type: string, props: Task_Props): any;
export declare function task(props: Task_Props): any;
export declare function testReport(type: string, props: TestReport_Props): any;
export declare function testReport(props: TestReport_Props): any;
export declare function testScript(type: string, props: TestScript_Props): any;
export declare function testScript(props: TestScript_Props): any;
export declare function verificationResult(type: string, props: VerificationResult_Props): any;
export declare function verificationResult(props: VerificationResult_Props): any;
export declare function visionPrescription(type: string, props: VisionPrescription_Props): any;
export declare function visionPrescription(props: VisionPrescription_Props): any;
