name: Docs

on:
  push:
    branches: [main]

jobs:
  build:
    name: 'Build docs to docs branch'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.13.2
      - name: Setup node ${{ matrix.node-version }}
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Setup pnpm
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm -r run build docs
      - name: Copy docs to docs branch
        run: pnpm exec .github/workflows/docs.sh
